name: Release Magisk module LTE

on:
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Read module.prop
        id: module_prop
        run: |
          VERSION=$(grep "version=" p9_lte_combos_mod/module.prop | cut -d= -f2)
          VERSIONCODE=$(grep "versionCode=" p9_lte_combos_mod/module.prop | cut -d= -f2)
          echo "MOD_VERSION=$VERSION" >> $GITHUB_ENV
          echo "MOD_VERSIONCODE=$VERSIONCODE" >> $GITHUB_ENV
          echo "RELEASE_TAG=LTE-v$VERSIONCODE" >> $GITHUB_ENV

      - name: Zip folder
        working-directory: ./
        run: |
          cd p9_lte_combos_mod
          zip -r ../p9_lte_combos_mod_v${{ env.MOD_VERSION }}.zip ./*
          cd ..

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: Release ${{ env.RELEASE_TAG }}
          draft: false
          prerelease: false
          files: |
            p9_lte_combos_mod_v${{ env.MOD_VERSION }}.zip

      - name: Update updater JSON
        run: |
          cat > updaterLTE.json << EOF
          {
            "version": "${{ env.MOD_VERSION }}",
            "versionCode": ${{ env.MOD_VERSIONCODE }},
            "zipUrl": "https://github.com/${{ github.repository }}/releases/download/${{ env.RELEASE_TAG }}/p9_lte_combos_mod_v${{ env.MOD_VERSION }}.zip",
            "changelog": "https://raw.githubusercontent.com/${{ github.repository }}/main/changelog-LTE.md"
          }
          EOF

      - name: Commit and push updater JSON
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add updaterLTE.json
          git commit -m "Update updaterLTE.json for version ${{ env.MOD_VERSION }}"
          git push

      - name: Send to Telegram
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID_1: ${{ secrets.TELEGRAM_CHAT_ID_1_GROUP }}
          CHAT_ID_2: ${{ secrets.TELEGRAM_CHAT_ID_2 }}
        run: |
          # Send to first chat
          curl -F document=@"p9_lte_combos_mod_v${{ env.MOD_VERSION }}.zip" \
          -F caption="New LTE Module Release ${{ env.RELEASE_TAG }}" \
          "https://api.telegram.org/bot${BOT_TOKEN}/sendDocument?chat_id=${CHAT_ID_1}"
          
          # Send to second chat
          curl -F document=@"p9_lte_combos_mod_v${{ env.MOD_VERSION }}.zip" \
          -F caption="New LTE Module Release ${{ env.RELEASE_TAG }}" \
          "https://api.telegram.org/bot${BOT_TOKEN}/sendDocument?chat_id=${CHAT_ID_2}"
