name: Release Magisk module NR

on:
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Read module.prop
        id: module_prop
        run: |
          VERSION=$(grep "version=" p9_nr_platform_mod/module.prop | cut -d= -f2)
          VERSIONCODE=$(grep "versionCode=" p9_nr_platform_mod/module.prop | cut -d= -f2)
          echo "MOD_VERSION=$VERSION" >> $GITHUB_ENV
          echo "MOD_VERSIONCODE=$VERSIONCODE" >> $GITHUB_ENV
          echo "RELEASE_TAG=NR-v$VERSIONCODE" >> $GITHUB_ENV

      - name: Zip folder
        working-directory: ./
        run: |
          cd p9_nr_platform_mod
          zip -r ../p9_nr_platform_mod_v${{ env.MOD_VERSION }}.zip ./*
          cd ..

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: Release ${{ env.RELEASE_TAG }}
          draft: false
          prerelease: false
          files: |
            p9_nr_platform_mod_v${{ env.MOD_VERSION }}.zip

      - name: Update updater JSON
        run: |
          cat > updaterNR.json << EOF
          {
            "version": "${{ env.MOD_VERSION }}",
            "versionCode": ${{ env.MOD_VERSIONCODE }},
            "zipUrl": "https://github.com/${{ github.repository }}/releases/download/${{ env.RELEASE_TAG }}/p9_nr_platform_mod_v${{ env.MOD_VERSION }}.zip",
            "changelog": "https://raw.githubusercontent.com/${{ github.repository }}/main/changelog-NR.md"
          }
          EOF

      - name: Commit and push updater JSON
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add updaterNR.json
          git commit -m "Update updaterNR.json for version ${{ env.MOD_VERSION }}"
          git push
